
version: "3.9" # optional since v1.27.0
services:
  frontend:
    build:
      context: .
      args:
        API_URL: ${APP_URL}
        APP_TITLE: ${APP_TITLE}
        APP_DESCRIPTION: ${APP_DESCRIPTION}
        APP_ICON: ${APP_ICON}
    ports:
      - ${APP_PORT}:3001